import pyautogui
import time
import pyperclip
import os
header = input("What is the header title of this program?: ")
progName = input("What should the name of this file be?: ")
buildString = "import os\nos.system(\"clear\")\nfrom rich.console import Console\nfrom rich.markdown import Markdown\nfrom rich.table import Table\nconsole = Console()\nMD_TITLE = Markdown(\"# {}\")\ndef defaultDisplay():\n\tos.system(\"clear\")\n\tconsole.print(MD_TITLE)\n\t\n\ndef logic(entered, enteredList):\n\tpass\n\nwhile True:\n\tpass".format(header)
pyperclip.copy(buildString)
pyautogui.hotkey("ctrl", "alt", "t")
time.sleep(1)
pyautogui.write("cd programming")
pyautogui.press("enter")
time.sleep(0.5)
pyautogui.write("cd dconsole-python")
pyautogui.press("enter")
time.sleep(0.5)
pyautogui.write(("vim {}.py".format(progName)))
pyautogui.press("enter")
time.sleep(0.5)
pyautogui.press("i")
time.sleep(0.5)
pyautogui.hotkey("ctrl", "shift", "v")
time.sleep(0.5)
pyautogui.press("esc")
time.sleep(0.5)
pyautogui.write(":wq")
pyautogui.press("enter")
time.sleep(0.5)
pyautogui.hotkey("alt", "f4")
print("{}.py created and written to".format(progName))
stop = input("Hit ENTER to proceed and terminate this program.")